import {
  Product,
  AddOnItem,
  DeliverySlot,
  DistrictZone,
  EmotionOption,
  CustomerReview,
  BlogPost,
} from "@/types";

export const BUSINESS_INFO = {
  name: "Muş Çiçekçi",
  legalName: "Taşdemir Çiçekçilik",
  foundingYear: 2017,
  tagline: "Her Çiçeğin Bir Hikâyesi Var",
  subTagline: "Muş'ta aynı gün teslim edilen, özenle hazırlanan çiçekler.",
  phone: "0 544 549 30 46",
  landline: "0436 212 30 46",
  whatsapp: "905445493046",
  email: "vehbitasdemir@gmail.com",
  address: "Kültür Mahallesi İstasyon Caddesi 168. Sokak, Yeni Öğretmen Evi Karşısı Büyük Eczane yanı, 49100 Muş",
  workingHours: "Haftanın 7 Günü: 08:30 – 22:00",
  instagramUrl: "https://www.instagram.com/tasdemircicekcilik2/",
  facebookUrl: "https://www.facebook.com/profile.php?id=100063621848036",
  iban: "TR54 0006 2000 0001 2345 6789 01",
  bankName: "Garanti BBVA - Muş Şubesi",
  accountHolder: "Vehbi Taşdemir - Taşdemir Çiçekçilik",
};

export const EMOTION_OPTIONS: EmotionOption[] = [
  {
    id: "seni-seviyorum",
    slug: "sevgiliye",
    title: "SENİ SEVİYORUM",
    subtitle: "Aşk, Tutku & Saf Bağlılık",
    emotionName: "Aşk & Tutku",
    colorHint: "#6F2232",
    accentColor: "from-rose-900 to-red-950",
    flowerType: "Kırmızı Ekvador Gülleri",
    description: "Kelimelerin yetmediği anlarda en derin duygularınızı taze kırmızı güller anlatsın.",
    targetCategory: "guller",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=900&auto=format&fit=crop",
  },
  {
    id: "iyi-ki-dogdun",
    slug: "dogum-gunu",
    title: "İYİ Kİ DOĞDUN",
    subtitle: "Neşe, Coşku & Yeni Bir Yaş",
    emotionName: "Doğum Günü",
    colorHint: "#E7B9A5",
    accentColor: "from-amber-800 to-orange-900",
    flowerType: "Renkli Gerberalar & Papatyalar",
    description: "Günün enerjisini yükselten, taptaze mevsim renkleriyle harmanlanmış buketler.",
    targetCategory: "buketler",
    imageUrl: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?q=80&w=900&auto=format&fit=crop",
  },
  {
    id: "bir-omur-mutluluk",
    slug: "soz-nisan-dugun",
    title: "BİR ÖMÜR MUTLULUK",
    subtitle: "Söz, Nişan, Düğün & Tebrik",
    emotionName: "Kutlama & Birliktelik",
    colorHint: "#18392B",
    accentColor: "from-emerald-900 to-teal-950",
    flowerType: "Beyaz Güller & Lüks Aranjmanlar",
    description: "Yeni bir hayatın ilk adımında zarafetiyle büyüleyen görkemli düğün ve nişan çelenkleri.",
    targetCategory: "celenkler",
    imageUrl: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=900&auto=format&fit=crop",
  },
  {
    id: "gecmis-olsun",
    slug: "gecmis-olsun",
    title: "GEÇMİŞ OLSUN",
    subtitle: "Huzur, Şifa & Canlandırıcı Yeşil",
    emotionName: "Şifa & Moral",
    colorHint: "#365B45",
    accentColor: "from-emerald-800 to-green-950",
    flowerType: "Beyaz Orkideler & Ökaliptus",
    description: "Huzur ve yaşam enerjisi fısıldayan saf orkide ve taze botanik yapraklar.",
    targetCategory: "orkideler",
    imageUrl: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?q=80&w=900&auto=format&fit=crop",
  },
  {
    id: "hos-geldin",
    slug: "yeni-bebek",
    title: "HOŞ GELDİN DÜNYAYA",
    subtitle: "Masumiyet & Yeni Bir Hayat",
    emotionName: "Yeni Bebek",
    colorHint: "#C98E98",
    accentColor: "from-pink-900 to-rose-950",
    flowerType: "Pastel Çiçekler & Papatyalar",
    description: "Minik bir mucizenin gelişini kutlamak için en naif pastel tonlar ve sevimli detaylar.",
    targetCategory: "buketler",
    imageUrl: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?q=80&w=900&auto=format&fit=crop",
  },
  {
    id: "yanindayim",
    slug: "cenaze",
    title: "HER AN YANINDAYIM",
    subtitle: "Hüzün, Vefa & Saygı",
    emotionName: "Vefa & Taziye",
    colorHint: "#20221F",
    accentColor: "from-stone-800 to-zinc-950",
    flowerType: "Lilyumlar & Saygı Çelenkleri",
    description: "Zor günlerde desteğinizi ve derin saygınızı ifade eden asil taziye çelenkleri.",
    targetCategory: "celenkler",
    imageUrl: "https://images.unsplash.com/photo-1509223197845-458d87318791?q=80&w=900&auto=format&fit=crop",
  },
];

export const DISTRICT_ZONES: DistrictZone[] = [
  {
    id: "merkez",
    name: "Muş Merkez",
    sameDay: true,
    deliveryFee: 0,
    estimatedHours: "Aynı Gün (2-3 Saat İçinde)",
    neighborhoods: [
      "Kültür Mahallesi",
      "Sunay Mahallesi",
      "Muratpaşa Mahallesi",
      "Zafer Mahallesi",
      "Hürriyet Mahallesi",
      "Saray Mahallesi",
      "Yeşilyurt Mahallesi",
      "Karşıyaka Mahallesi",
      "Kale Mahallesi",
      "Bağlar Mahallesi",
      "Muş Alparslan Üniversitesi Kampüsü",
      "Muş Devlet Hastanesi Çevresi",
    ],
  },
  {
    id: "haskoy",
    name: "Hasköy",
    sameDay: true,
    deliveryFee: 150,
    estimatedHours: "Aynı Gün (3-4 Saat)",
    neighborhoods: ["Hasköy Merkez", "Aşağıüçdam", "Karakütük", "Koçköy"],
  },
  {
    id: "korkut",
    name: "Korkut",
    sameDay: true,
    deliveryFee: 200,
    estimatedHours: "Aynı Gün (Özel Kurye)",
    neighborhoods: ["Korkut Merkez", "Altınova", "Kümbet"],
  },
  {
    id: "bulanik",
    name: "Bulanık",
    sameDay: true,
    deliveryFee: 250,
    estimatedHours: "Aynı Gün (Özel Kurye)",
    neighborhoods: ["Bulanık Merkez", "Yoncalı", "Rüstemgedik"],
  },
  {
    id: "malazgirt",
    name: "Malazgirt",
    sameDay: true,
    deliveryFee: 300,
    estimatedHours: "Aynı Gün (Özel Kurye)",
    neighborhoods: ["Malazgirt Merkez", "Konakkuran"],
  },
  {
    id: "varto",
    name: "Varto",
    sameDay: true,
    deliveryFee: 250,
    estimatedHours: "Aynı Gün (Özel Kurye)",
    neighborhoods: ["Varto Merkez", "Çaylar"],
  },
];

export const DELIVERY_SLOTS: DeliverySlot[] = [
  {
    id: "slot-1",
    label: "Sabah Teslimatı",
    startTime: "09:00",
    endTime: "12:00",
    isAvailable: true,
  },
  {
    id: "slot-2",
    label: "Öğle Teslimatı",
    startTime: "12:00",
    endTime: "15:00",
    isAvailable: true,
  },
  {
    id: "slot-3",
    label: "İkindi Teslimatı",
    startTime: "15:00",
    endTime: "18:00",
    isAvailable: true,
  },
  {
    id: "slot-4",
    label: "Akşam Teslimatı",
    startTime: "18:00",
    endTime: "21:30",
    isAvailable: true,
  },
];

export const CARD_TEMPLATES = [
  {
    id: "t1",
    category: "Sevgiliye & Aşk",
    text: "Gözlerinin değdiği her yer bahar bahçe... İyi ki varsın, seni çok seviyorum.",
  },
  {
    id: "t2",
    category: "Doğum Günü",
    text: "Yeni yaşın sana tüm güzellikleri, sağlık ve huzuru getirsin. Doğum günün kutlu olsun!",
  },
  {
    id: "t3",
    category: "Geçmiş Olsun",
    text: "Bir an önce sağlığına kavuşup aramıza dönmen dileğiyle. Çok geçmiş olsun, dualarımız seninle.",
  },
  {
    id: "t4",
    category: "Yeni İş / Tebrik",
    text: "Yeni görevinde başarılarının katlanarak devam etmesini dilerim. Yolun açık olsun!",
  },
  {
    id: "t5",
    category: "Özür Dilerim",
    text: "Seni kırmak asla istemezdim. Kalbimin en derin yerinden gelen samimi bir özürle affını diliyorum.",
  },
];

export const ADD_ON_ITEMS: AddOnItem[] = [
  {
    id: "addon-choc-1",
    name: "Artisan Belçika Çikolatası Kutusu (16 Adet)",
    category: "chocolate",
    price: 380,
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=600&auto=format&fit=crop",
    description: "Özel ahşap kutuda taze el yapımı fındıklı ve karamelli pralinler.",
  },
  {
    id: "addon-teddy-1",
    name: "Premium Yumuşak Peluş Ayıcık (35 cm)",
    category: "teddy",
    price: 320,
    image: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?q=80&w=600&auto=format&fit=crop",
    description: "Kadife yumuşaklığında, kırmızı fiyonklu sevimli hediye ayıcık.",
  },
  {
    id: "addon-vase-1",
    name: "İskandinav Mat Seramik Vazo",
    category: "vase",
    price: 260,
    image: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=600&auto=format&fit=crop",
    description: "Minimalist sage yeşili dokulu, uzun ömürlü seramik masa vazosu.",
  },
  {
    id: "addon-balloon-1",
    name: "Uçan Helyum Kalp Balon Seti (3'lü)",
    category: "balloon",
    price: 180,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=600&auto=format&fit=crop",
    description: "Işıltılı sedefli kırmızı helyum uçan balon buketi.",
  },
];

export const PRODUCTS_CATALOG: Product[] = [
  {
    id: "52",
    slug: "11-adet-kirmizi-gul-buketi",
    name: "11 Adet Kırmızı Gül Buketi",
    subtitle: "Saf Aşkın Zamansız Zarafeti",
    price: 1520,
    originalPrice: 1600,
    category: "guller",
    occasions: ["sevgiliye", "yildonumu", "dogum-gunu"],
    flowerType: "Kırmızı Gül",
    flowerCount: 11,
    color: "Kırmızı",
    description: "Özenle seçilmiş 11 adet iri başlı yerli ve ithal taze kırmızı gül, okaliptus dalları ve lüks keten kumaş ambalajıyla hazırlanmıştır.",
    careInstructions: "Vazoya koymadan önce sap uçlarını 45 derecelik açıyla 1 cm kesin. Suyu iki günde bir yenileyiniz.",
    meaning: "11 gül, 'Sen benim hayatımın tek ve en değerli aşkısın' anlamını taşır.",
    images: [
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1548094891-c4969f667149?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockCount: 25,
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: "55",
    slug: "11-adet-beyaz-gul-buketi",
    name: "11 Adet Beyaz Gül Buketi",
    subtitle: "Masumiyetin ve Saygının Simgesi",
    price: 1620,
    originalPrice: 1720,
    category: "guller",
    occasions: ["soz-nisan-dugun", "yildonumu", "ozur-dilerim"],
    flowerType: "Beyaz Gül",
    flowerCount: 11,
    color: "Beyaz",
    description: "Kusursuz saflıkta 11 adet iri taç yapraklı beyaz gül, cipsofilya ve asil zümrüt yeşili yapraklarla bezenmiştir.",
    careInstructions: "Direkt güneş ışığından uzak, serin bir alanda sergileyiniz. Sapları düzenli temizleyiniz.",
    meaning: "Beyaz gül masumiyeti, yeni başlangıçları ve ebedi sadakati simgeler.",
    images: [
      "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockCount: 18,
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: "64",
    slug: "cift-dalli-beyaz-orkide",
    name: "Çift Dallı Beyaz Phalaenopsis Orkide",
    subtitle: "Asil ve Uzun Ömürlü Zarafet",
    price: 1500,
    originalPrice: 1750,
    category: "orkideler",
    occasions: ["yeni-is", "gecmis-olsun", "acilis-toren", "dogum-gunu"],
    flowerType: "Phalaenopsis Orkide",
    flowerCount: 2,
    color: "Beyaz",
    description: "Özel seramik saksısında, bol tomurcuklu 2 dal taze beyaz Phalaenopsis orkide. Haftalarca çiçek açarak mekanlara seçkin bir hava katar.",
    careInstructions: "Haftada 1 kez oda sıcaklığındaki suyla daldırma yöntemiyle sulayın. Aydınlık ama direkt güneş almayan yeri sever.",
    meaning: "Orkide zarafet, asalet ve derin saygının temsilcisidir.",
    images: [
      "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?q=80&w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockCount: 14,
    rating: 5.0,
    reviewCount: 42,
  },
  {
    id: "67",
    slug: "cift-dalli-mor-orkide",
    name: "Çift Dallı Mor Phalaenopsis Orkide",
    subtitle: "Büyüleyici Egzotik Tonlar",
    price: 1550,
    originalPrice: 1750,
    category: "orkideler",
    occasions: ["dogum-gunu", "yeni-is", "yildonumu"],
    flowerType: "Phalaenopsis Orkide",
    flowerCount: 2,
    color: "Mor",
    description: "Canlı fuşya ve derin mor taç yapraklarıyla göz kamaştıran çift dallı lüks orkide sunumu.",
    careInstructions: "Köklerin hava almasını sağlayın. Tabağında fazla su bekletmeyiniz.",
    meaning: "Mor orkide hayranlık, yaratıcılık ve görkemi simgeler.",
    images: [
      "https://images.unsplash.com/photo-1566999537091-c07456b576ae?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: false,
    isFeatured: true,
    inStock: true,
    stockCount: 9,
    rating: 4.9,
    reviewCount: 19,
  },
  {
    id: "58",
    slug: "cam-vazoda-11-gul",
    name: "Cam Vazoda 11 Kırmızı Gül",
    subtitle: "Kristal Zarafet İçinde Romantizm",
    price: 1600,
    originalPrice: 1900,
    category: "vazoda-cicekler",
    occasions: ["sevgiliye", "yildonumu"],
    flowerType: "Kırmızı Gül",
    flowerCount: 11,
    color: "Kırmızı",
    description: "Şeffaf silindir cam vazo içerisine okaliptus ve dekoratif çakıl taşlarıyla özel olarak dizayn edilmiş 11 kadife kırmızı gül.",
    careInstructions: "Vazo suyunu 2 günde bir tazeleyip serin odada tutunuz.",
    meaning: "Ev ve ofis masaları için anında hazır, zahmetsiz aşk jesti.",
    images: [
      "https://images.unsplash.com/photo-1548094891-c4969f667149?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: true,
    isFeatured: false,
    inStock: true,
    stockCount: 12,
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: "70",
    slug: "gul-ve-lilyum-buketi",
    name: "Asil Gül ve Lilyum Buketi",
    subtitle: "Büyüleyici Koku & Asalet",
    price: 1200,
    originalPrice: 1350,
    category: "buketler",
    occasions: ["dogum-gunu", "yildonumu", "ozur-dilerim", "gecmis-olsun"],
    flowerType: "Gül ve Lilyum",
    flowerCount: 15,
    color: "Pembe ve Beyaz",
    description: "Kokulu pembe Casablanca lilyumlar, pudra güller ve taze mevsim yeşilliklerinin ahenkli dansı.",
    careInstructions: "Açan lilyumların polenlerini nazikçe alarak çiçeğin ömrünü uzatabilirsiniz.",
    meaning: "Lilyum saflığı ve yeniden doğuşu müjdeler.",
    images: [
      "https://images.unsplash.com/photo-1509223197845-458d87318791?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockCount: 20,
    rating: 4.8,
    reviewCount: 27,
  },
  {
    id: "72",
    slug: "renkli-gerbera-buketi",
    name: "Güneş Bahçesi Renkli Gerbera Buketi",
    subtitle: "Yaşama Sevinci ve Pozitif Enerji",
    price: 1200,
    originalPrice: 1350,
    category: "buketler",
    occasions: ["dogum-gunu", "gecmis-olsun", "yeni-is", "yeni-bebek"],
    flowerType: "Gerbera",
    flowerCount: 12,
    color: "Çok Renkli",
    description: "Sarı, turuncu, fuşya ve kırmızı iri gerberaların cipsofilya ile harmanlandığı, sıcak yaz esintisi getiren özel buket.",
    careInstructions: "Saplarını az su dolu vazoya koyun, suyu sık sık tazeleyin.",
    meaning: "Gerbera neşe, masumiyet ve samimiyetin ifadesidir.",
    images: [
      "https://images.unsplash.com/photo-1561181286-d3fee7d55364?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: false,
    isFeatured: false,
    inStock: true,
    stockCount: 15,
    rating: 4.7,
    reviewCount: 16,
  },
  {
    id: "76",
    slug: "kirmizi-antoryum",
    name: "Görkemli Kırmızı Antoryum (Flamingo Çiçeği)",
    subtitle: "Aylarca Çiçek Açan Heykelimsi Form",
    price: 1200,
    originalPrice: 1350,
    category: "saksi-bitkileri",
    occasions: ["yeni-is", "acilis-toren", "gecmis-olsun"],
    flowerType: "Antoryum",
    color: "Kırmızı / Yeşil",
    description: "Parlak kırmızı kalp şeklindeki çiçekleriyle ofis ve salonların vazgeçilmez hava temizleyici lüks salon bitkisi.",
    careInstructions: "Nemli ortamları sever. Yapraklarına ılık su püskürtülmesi gelişimini hızlandırır.",
    meaning: "Antoryum misafirperverlik, bolluk ve mutluluk simgesidir.",
    images: [
      "https://images.unsplash.com/photo-1596724817757-b50a31744b82?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: false,
    isFeatured: true,
    inStock: true,
    stockCount: 8,
    rating: 4.9,
    reviewCount: 22,
  },
  {
    id: "84",
    slug: "buyuleyici-orman-teraryum",
    name: "Büyüleyici Orman Cam Teraryum",
    subtitle: "El Yapımı Minyatür Bir Ekosistem",
    price: 1500,
    originalPrice: 1750,
    category: "teraryumlar",
    occasions: ["yeni-is", "dogum-gunu", "yildonumu"],
    flowerType: "Sukulent & Kaktüs",
    color: "Yeşil / Doğal Ahşap",
    description: "Özel el üfleme cam fanus içerisinde doğal yosunlar, şoklanmış kuru çiçekler, sukulentler ve ahşap figürlerle sanatsal peyzaj.",
    careInstructions: "15 günde bir fısfıs ile çok az sulanmalıdır. Gölge-yarı aydınlık mekan için idealdir.",
    meaning: "Sonsuz sevgi ve uzun ömürlü dostluğun minyatür dünyası.",
    images: [
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockCount: 10,
    rating: 5.0,
    reviewCount: 35,
  },
  {
    id: "89",
    slug: "dugun-celengi-beyaz-kirmizi",
    name: "Görkemli Düğün & Tören Çelengi",
    subtitle: "En Önemli Günlerin Saygın Temsilcisi",
    price: 3500,
    originalPrice: 4000,
    category: "celenkler",
    occasions: ["soz-nisan-dugun", "acilis-toren"],
    flowerType: "Gerbera & Glayöl",
    flowerCount: 80,
    color: "Beyaz ve Kırmızı",
    description: "Muş düğün ve açılış törenlerine özel, üzerine istenen isim ve unvan yazılı saten kurdele ile hazırlanan 2 metre boyunda görkemli ayaklı çelenk.",
    careInstructions: "Tören saatinden 1 saat önce mekan görevlisine tutanakla teslim edilir.",
    meaning: "Tebrik ve kurumsal saygının en prestijli göstergesidir.",
    images: [
      "https://images.unsplash.com/photo-1546842931-886c185b4c8c?q=80&w=900&auto=format&fit=crop",
    ],
    sameDayDelivery: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockCount: 5,
    rating: 5.0,
    reviewCount: 48,
  },
];

export const CUSTOMER_REVIEWS: CustomerReview[] = [
  {
    id: "rev-1",
    authorName: "Ahmet B.",
    city: "Muş Merkez",
    productName: "11 Adet Kırmızı Gül Buketi",
    rating: 5,
    comment: "Eşimin doğum günü için saat 11'de sipariş verdim, 13:30'da Kültür Mahallesi'ne ulaştı. Güller taptazeydi, el yazısı kart detayı çok zarifti.",
    date: "12 Eylül 2026",
    verifiedPurchase: true,
  },
  {
    id: "rev-2",
    authorName: "Merve K.",
    city: "Muş / Alparslan Kampüsü",
    productName: "Çift Dallı Beyaz Orkide",
    rating: 5,
    comment: "Hocamızın profesörlük tebriği için gönderdik. Saksısı ve ambalajı fotoğraftakinden bile daha kaliteli çıktı. Taşdemir Çiçekçilik'e teşekkürler.",
    date: "8 Eylül 2026",
    verifiedPurchase: true,
  },
  {
    id: "rev-3",
    authorName: "Serkan Y.",
    city: "Hasköy",
    productName: "Görkemli Düğün Çelengi",
    rating: 5,
    comment: "Hasköy'deki akrabamızın düğünü için istedik. Zamanında ve eksiksiz ulaştı. Kurdele yazısı çok netti.",
    date: "4 Eylül 2026",
    verifiedPurchase: true,
  },
  {
    id: "rev-4",
    authorName: "Zeynep T.",
    city: "Muş / Sunay Mah.",
    productName: "Büyüleyici Orman Cam Teraryum",
    rating: 5,
    comment: "Kardeşimin yeni ofisi için harika bir hediye oldu. Camın içinde gerçek bir doğa parçası var gibi. Çok teşekkür ederiz!",
    date: "29 Ağustos 2026",
    verifiedPurchase: true,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    slug: "orkide-bakimi-nasil-yapilir",
    title: "Orkide Bakımının Püf Noktaları: Çiçekleri Aylarca Nasıl Korunur?",
    excerpt: "Evinize veya ofisinize gelen zarif Phalaenopsis orkidenin haftalarca canlı kalmasını sağlayacak doğru sulama, ışık ve nem tüyoları.",
    content: `Orkideler sanıldığının aksine kaprisli değil, yalnızca doğal ortamlarındaki ritmi arayan özel bitkilerdir. Doğada ağaç gövdelerine tutunarak yaşarlar; bu nedenle köklerinin nefes alması ve suyun içinde boğulmaması hayati önem taşır.

1. Sulama Rutini: Orkidenizi haftada bir defa oda sıcaklığındaki içme suyu dolu bir kaba saksısıyla daldırın. 10-15 dakika bekledikten sonra fazla suyu tamamen süzün.
2. Işık İhtiyacı: Direkt güneş ışığı yaprakları yakabilir. Tül arkasından gelen aydınlık, filtrelenmiş gün ışığı orkideler için idealdir.
3. Kök Rengi Göstergesi: Kökler gümüşi griye döndüğünde sulama zamanı gelmiştir. Kökler parlak yeşilse su ihtiyacı yoktur.`,
    category: "Çiçek Bakımı",
    readTime: "4 dk okuma",
    date: "10 Eylül 2026",
    author: "Vehbi Taşdemir",
    image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?q=80&w=900&auto=format&fit=crop",
    tags: ["Orkide", "Ev Bitkisi", "Sulama", "Muş Çiçek"],
  },
  {
    id: "blog-2",
    slug: "guller-vazoda-nasil-daha-uzun-dayanir",
    title: "Vazodaki Güllerin Ömrünü 2 Katına Çıkaran 5 Doğal Yöntem",
    excerpt: "Gül buketinizin ilk günkü tazeliğini ve büyüleyici kokusunu 10 güne kadar korumanın botanik sırları.",
    content: `Özel bir anda hediye gelen kırmızı veya beyaz güllerin solup gitmesi herkesi üzer. Doğru adımlarla gül buketinizin ömrünü 10-12 güne kadar rahatlıkla uzatabilirsiniz.

- 45 Derecelik Kesim: Sap uçlarını su altında 45 derecelik açıyla kesin. Bu, su emilim yüzeyini maksimize eder ve hava kabarcığı oluşmasını engeller.
- Su Seviyesindeki Yaprakları Temizleyin: Su içinde kalan yapraklar bakteriye sebep olarak suyun kalitesini bozar.
- 2 Günde Bir Taze Su: Vazonuzun suyunu gün aşırı değiştirin ve serin bir ortamda tutun.`,
    category: "Rehber",
    readTime: "3 dk okuma",
    date: "5 Eylül 2026",
    author: "Taşdemir Florist Ekibi",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=900&auto=format&fit=crop",
    tags: ["Gül Bakımı", "Buket", "Püf Noktaları"],
  },
  {
    id: "blog-3",
    slug: "musa-ayni-gun-cicek-gonderimi-nasil-isler",
    title: "Muş'ta Aynı Gün Çiçek Gönderimi: Dakikalar İçinde Kapıda",
    excerpt: "Muş Merkez ve çevre ilçelere en hızlı, güvenilir ve özenli çiçek siparişi nasıl verilir?",
    content: `Unutulan bir yıldönümü veya son dakikada gelen güzel bir haber... Taşdemir Çiçekçilik olarak Muş içi tüm siparişlerinizi aynı gün usta ellerde hazırlayıp kendi özel korumalı araçlarımızla ulaştırıyoruz.`,
    category: "Lojistik & Teslimat",
    readTime: "2 dk okuma",
    date: "1 Eylül 2026",
    author: "Muş Çiçekçi",
    image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=900&auto=format&fit=crop",
    tags: ["Muş Çiçekçi", "Aynı Gün Teslimat", "Hızlı Gönderi"],
  },
];
